services:
  frontend_and_gateway:
    build: ./frontend/vite-project
    ports:
      - 80:80
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/workshop
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: